parameters:
  azureServiceConnection: ''
  resourceGroup: ''
  location: ''
  deploymentLocation: 'westeurope'
  bicepFile: ''
  environmentName: ''
  principalId: ''
  dbAdminPassword: ''
  dbAppUserPassword: ''


jobs:
  - job: DeployInfra
    displayName: 'Deploy IaC (Bicep)'
    pool:
        name: SelfHosted
    steps:
      - task: AzureCLI@2
        displayName: 'Deploy Bicep'
        inputs:
          azureSubscription: ${{ parameters.azureServiceConnection }}
          scriptType: 'pscore'
          scriptLocation: 'inlineScript'
          inlineScript: |
            az deployment sub create `
            --location "${{ parameters.deploymentLocation }}" `
            --template-file "${{ parameters.bicepFile }}" `
            --parameters environmentName="${{ parameters.environmentName }}" `
            --parameters location="${{ parameters.location }}" `
            --parameters resourceGroupName="${{ parameters.resourceGroup }}" `
            --parameters principalId="${{ parameters.principalId }}" `
            --parameters dbAdminPassword="${{ parameters.dbAdminPassword }}" `
            --parameters dbAppUserPassword="${{ parameters.dbAppUserPassword }}"


